# Species Diversity of taxa at the family level
# Code was generated by Dr. Noelle Beckman

# Table was filtered by removing any OTUs with less than 10 phylotypes in less than 10 samples

# Diversity values was ran using iNEXT on Ohio Supercomputer Center using L5 filtered table
# output was 
# (1) "diveristy-order0-" for q = 0
# (2) "diversity-pointestimate-minsize" for q = 1
# (3) "diversity-pointestimate-mincoverage" for q = 2

# I used those 3 dataframes to make a .Rdata file so that all hill numbers were in the same file

# Make sure you have "Functions.R"


require(lme4)
require(xtable)
require(lattice)
require("LMERConvenienceFunctions")
require(AICcmodavg)
require(nlme)
library(tidyr)
library(dplyr)


# Load diversity data.table. Change location. 
location="/Users/kaylacross/Library/CloudStorage/OneDrive-TheOhioStateUniversity/Frass_Paper/Sabree_L5/plots wo cellulose 5 8/L5 diversity/rerun_code"

# Number of simulations for bootstrapping
boot_sims=1000

# Source functions
source(file.path(location,"Functions.R"))

file.name=c("diversity_min_size.Rdata")

load("~/Library/CloudStorage/OneDrive-TheOhioStateUniversity/Frass_Paper/Sabree_L5/plots wo cellulose 5 8/L5 diversity/rerun_code/diversity_min_size.Rdata")

# restructuring the data so that each hill number has it's own column and removing the LCL and UCL values
data <- pivot_wider(diversity_min_size, 
                    names_from = order,
                    values_from = qD,
                    id_cols = c(site, qD.LCL, qD.UCL))

q0 <- data[, 1:4]
q0 <- na.omit(q0)

q1 <- data[, c(1:3, 5)]
q1 <- na.omit(q1)

q2 <- data[, c(1:3, 6)]
q2 <- na.omit(q2)

redata <- cbind.data.frame(q0[, c(1,4)], q1[, 4], q2[, 4])

diversity = diversity_min_size # keeping original just in case

diversity_min_size <- redata %>% rename("Srar" = '0', "Shan" = '1', "Simp" = '2')



# Break up ID to diet, individuals, and week
diversity_min_size$diet = substring(diversity_min_size$site,1,2)
diversity_min_size$ind = substring(diversity_min_size$site,4,4)
diversity_min_size$week = substring(diversity_min_size$site,6,6)

# Rename individuals so each one is unique
diversity_min_size$ind = as.numeric(diversity_min_size$ind)
diversity_min_size$individual=vector(mode="numeric", length=length(diversity_min_size$ind))
diversity_min_size[diversity_min_size$diet=="DF","individual"] =
  diversity_min_size[diversity_min_size$diet=="DF", "ind"]
diversity_min_size[diversity_min_size$diet=="HN","individual"] =
  diversity_min_size[diversity_min_size$diet == "HN", "ind"] + 7 
diversity_min_size[diversity_min_size$diet=="LN","individual"] =
  diversity_min_size[diversity_min_size$diet == "LN", "ind"] + 13 		

# Make diet, individual, and ID factors. Weeks is assumed to be continuous.
diversity_min_size$diet=as.factor(diversity_min_size$diet)
diversity_min_size$ind=as.factor(diversity_min_size$ind)

diversity_min_size$individual=as.factor(diversity_min_size$individual)
diversity_min_size$site=as.factor(diversity_min_size$site)

diversity_min_size$week = as.numeric(diversity_min_size$week)
diversity_min_size$week0=diversity_min_size$week-1

### Species Richness
# LMM with correlated random intercept
div_index = c("Srar")
models <- lapply(div_index, function(x) {
  lmer(substitute(y ~ diet*week0+(1|individual), list(y =
                                                        as.name(x))),
       data = diversity_min_size)
})  
names(models) <- div_index 

summary(models[["Srar"]]) # this information is used in the paper for LMM results

confint_lmer <- list()
for (i in 1:length(div_index)){
  confint_lmer[[i]]<-tryCatch.W.E(confint(models[[i]],method="boot",nsim=boot_sims,boot.type="perc"))
} 
rm(i)
names(confint_lmer) <- div_index
save(confint_lmer,file="CI_Srar_min_size_withoutLN5to8.R")

confint_lmer[["Srar"]] # These are the confidence intervals found in the supplemental material

coef.Srar <- as.data.frame(coef(summary(models[["Srar"]])))

sr.conf <- confint_lmer[["Srar"]]$value
sr.conf2 <- sr.conf[-2, ]

sr.sd <- c(3.843, 0, 0 ) # 3.843 came from Random Effects Sd.Dev, which might change a litte if you rerun the code due to the bootstrapping

coef.Srar2 <- rbind.data.frame(sr.sd, coef.Srar)

LMM.table.Srar <- cbind.data.frame(coef.Srar2[, 1], sr.conf2)
colnames(LMM.table.Srar) <- c("Coefficient_Estimate", "2.5%", "97.5%")
rownames(LMM.table.Srar) <- c("SD among Individuals", "Intercept", "Protien Enriched", "Cellulose Enriched", "Week", "Protein x Week", "Cellulose x Week")

LMM.table.Srar <- format(LMM.table.Srar, scientific=F) # combinding data to be inputted into supplemental

write.csv(LMM.table.Srar, "/Users/kaylacross/Library/CloudStorage/OneDrive-TheOhioStateUniversity/Frass_Paper/Sabree_L5/plots wo cellulose 5 8/L5 diversity/rerun_code/LMM.table.Srar.csv")

# Residuals vs fitted and QQPlot of LMM with random intercept for Interpolated/Extrapolated Species Richness (using min reference size)
par(mfrow=c(1,2),mai=c(1,0.5,1,0.5))
plot.glmer(models[["Srar"]],title="Interpolated/Extrapolated \n Species Richness (min size)")


# Histogram and QQ plots of fitted random intercept for Interpolated/Extrapolated Speciess Richness (using min reference size)
par(mfrow=c(1,2),mai=c(1,0.5,1,0.5))
hist(ranef(models[["Srar"]])$individual[["(Intercept)"]],
     xlab=names(ranef(models[["Srar"]])$individual)[[1]],main="max size")     

qqnorm(ranef(models[["Srar"]])$individual[["(Intercept)"]],
       ylab=paste("Sample Quantiles",
                  names(ranef(models[["Srar"]])$individual)[[1]]))
qqline(ranef(models[["Srar"]])$individual[["(Intercept)"]])

# Random effects of intercept for linear mixed model of Interpolated/Extrapolated Species Richness (using min reference size)
# Residuals for each individual
plot(models[["Srar"]], individual ~ resid(., scaled=TRUE), 
     main="Residuals of Individual (Averaged over Week)")

# Plot of intercept of random effect
dotplot(ranef(models[["Srar"]],condVar=TRUE), scales = list(x = list(relation = "free")))



tableCI_Srar_min_size<-xtable(confint_lmer[["Srar"]]$value)
caption(tableCI_Srar_min_size)<-"95 Percent Bootstrapped Confidence Intervals for 
LMM of Interpolated/Extrapolated Species Richness"
label(tableCI_Srar_min_size)<-"Table:BSlmer_Srar_min_size"
tableCI_Srar_min_size


# The LMERConvenienceFunctions looks at the standard deviations above or below the mean. 
# In this case, I am using 3 standard deviations. 
# Checking for outliers with LMERConvenienceFunctions for Interpolated/Extrapolated Species Richness 
#   (using min reference size) using 3 standard deviations above and below the mean. 
mcp.fnc(models[["Srar"]], trim = 3)


# trim data on initial model residuals
diversity.trimmed.Srar = romr.fnc(models[["Srar"]], diversity_min_size, trim = 3)
# no data removed

tmp=diversity.trimmed.Srar$data
tmp$trimmed=T
tmp1=diversity.trimmed.Srar$data0
tmp1$orig=T
tmp2=merge(tmp,tmp1,all=TRUE,by=names(tmp)[-which(names(tmp)=="trimmed")])
tmp3=tmp2[which(is.na(tmp2$trimmed)),-c(which(names(tmp2)=="trimmed"),which(names(tmp2)=="wd"),which(names(tmp2)=="rstand"),which(names(tmp2)=="orig"))]
table_Sraroutlier<-xtable(tmp3)
label(table_Sraroutlier)<-"Table: OutlierSrar"
rm(tmp,tmp1,tmp2,tmp3)

table_Sraroutlier

modelSrar<-lmer(Srar ~ diet*week+(1|individual), data = diversity.trimmed.Srar$data)

mcp.fnc(modelSrar, trim = 3)

diversity.trimmed2 = romr.fnc(modelSrar, diversity.trimmed.Srar$data, trim = 3)
# 0 data removed

#Residuals vs fitted and QQPlot of LMM with random intercept for Srar after removing 2nd set of outlier
par(mfrow=c(1,2),mai=c(1,0.5,1,0.5))
plot.glmer(modelSrar,title="H without outliers")

# Histogram and QQ plots of fitted random intercept for Srar after removing second set of outliers based on 3 s.d
par(mfrow=c(1,2),mai=c(1,0.5,1,0.5))
hist(ranef(modelSrar)$individual[["(Intercept)"]],xlab=names(ranef(modelSrar)$individual)[[1]],main="")     

qqnorm(ranef(modelSrar)$individual[["(Intercept)"]],ylab=paste("Sample Quantiles",names(ranef(modelSrar)$individual)[[1]]))
qqline(ranef(modelSrar)$individual[["(Intercept)"]])

#Random effects of intercept for linear mixed model of Srar after removing second set of outliers (Richness.Rnw)
# Residuals for each individual
plot(modelSrar, individual ~ resid(., scaled=TRUE), main="Residuals of Individual 
     (Averaging across Weeks)")

# Plot of intercept of random effect
dotplot(ranef(modelSrar,condVar=TRUE), scales = list(x = list(relation = "free")))


confint_lmer_outlier2_Srar <-tryCatch.W.E(confint(modelSrar,method="boot",nsim=boot_sims, boot.type="perc"))

# When all weeks are present for cellulose, LN_3_6 (cellulose-enriched diet, individual 3, week 6)
# was an outlier. However, since we removed weeks 5 - 8, this is no longer an issue.

# Code adapted from http://glmm.wikidot.com/faq  
newdat_HN <- expand.grid(week0 = 1:8, diet=c("DF","HN"),`Srar`= 0)
newdat_LN <- expand.grid(week0 = 1:4, diet=c("LN"),`Srar`= 0)
newdat <- rbind(newdat_HN, newdat_LN)
mm <- model.matrix(terms(models[["Srar"]]),newdat)
newdat$`Srar`<-mm %*% fixef(models[["Srar"]])
# or predict(modelSrar,newdat,re.form=NA)
pvar1 <- diag(mm %*% tcrossprod(vcov(models[["Srar"]]),mm))
tvar1 <- pvar1+VarCorr(models[["Srar"]])$individual[1]## must be adapted for more complex models
newdat <- data.frame(
  newdat
  , plo = newdat$`Srar`-2*sqrt(pvar1)
  , phi = newdat$`Srar`+2*sqrt(pvar1)
  , tlo = newdat$`Srar`-2*sqrt(tvar1)
  , thi = newdat$`Srar`+2*sqrt(tvar1)
)
names(newdat)[names(newdat)=="q...0"] ="Srar"
require(ggplot2)
newdat$colors[newdat$diet=="DF"]="black"
newdat$colors[newdat$diet=="HN"]="cyan4"
newdat$colors[newdat$diet=="LN"]="darkorange"

newdat$colorsfill[newdat$diet=="DF"]="black"
newdat$colorsfill[newdat$diet=="HN"]="cyan4"
newdat$colorsfill[newdat$diet=="LN"]="darkorange"

newdat$shape[newdat$diet=="DF"]=22
newdat$shape[newdat$diet=="HN"]=21
newdat$shape[newdat$diet=="LN"]=23

newdat$lt[newdat$diet=="DF"]="solid"
newdat$lt[newdat$diet=="HN"]="solid"
newdat$lt[newdat$diet=="LN"]="solid"

write.csv(newdat, "SpeciesRich_nocell58_newdat.csv")

g0 <- ggplot(newdat, aes(x=week0, y=`Srar`))+
  geom_point(colour=newdat$colors,
             fill=newdat$colorsfill,shape=newdat$shape, cex=4)


g0 + geom_errorbar(aes(ymin = plo, ymax = phi),colour=newdat$colors,cex=1, linetype=newdat$lt) +
  labs (x ="", y = "Species Presence") +
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black",size=1),
        axis.title = element_text(size=20),
        axis.text = element_text(size=15))



# Shannon Diversity
# LMM with correlated random intercept
div_index = c("Shan")
models <- lapply(div_index, function(x) {
  lmer(substitute(y ~ diet*week0+(1|individual), list(y =
                                                        as.name(x))),
       data = diversity_min_size)
})  
names(models) <- div_index 

summary(models[["Shan"]]) # matches supplemental table

confint_lmer <- list()
for (i in 1:length(div_index)){
  confint_lmer[[i]]<-tryCatch.W.E(confint(models[[i]],method="boot",nsim=boot_sims,boot.type="perc"))
} 
rm(i)
names(confint_lmer) <- div_index
save(confint_lmer,file="/Users/kaylacross/Library/CloudStorage/OneDrive-TheOhioStateUniversity/Frass_Paper/Sabree_L5/plots wo cellulose 5 8/L5 diversity/rerun_code/CI_Shan_min_size.R")

confint_lmer[["Shan"]] # this will be a little bit different due to bootstraping, but shouldn't be too off

coef.Shan <- as.data.frame(coef(summary(models[["Shan"]])))

sh.conf <- confint_lmer[["Shan"]]$value
sh.conf2 <- sh.conf[-2, ]

sh.sd <- c(1.876, 0, 0 ) # 1.876 came from Random Effects Sd.Dev

coef.shan2 <- rbind.data.frame(sh.sd, coef.Shan)

LMM.table.shan <- cbind.data.frame(coef.shan2[, 1], sh.conf2)
colnames(LMM.table.shan) <- c("Coefficient_Estimate", "2.5%", "97.5%")
rownames(LMM.table.shan) <- c("SD among Individuals", "Intercept", "Protien Enriched", "Cellulose Enriched", "Week", "Protein x Week", "Cellulose x Week")

LMM.table.shan <- format(LMM.table.shan, scientific=F)

write.csv(LMM.table.shan, "/Users/kaylacross/Library/CloudStorage/OneDrive-TheOhioStateUniversity/Frass_Paper/Sabree_L5/plots wo cellulose 5 8/L5 diversity/rerun_code/LMM.table.shan.csv")

# Residuals vs fitted and QQPlot of LMM with random intercept for Interpolated/Extrapolated Shannon Diversity (using min reference size)
par(mfrow=c(1,2),mai=c(1,0.5,1,0.5))
plot.glmer(models[["Shan"]],title="Interpolated/Extrapolated \n Shannon Diversity (min size)")

# Histogram and QQ plots of fitted random intercept for Interpolated/Extrapolated Speciess Shannon (using min reference size). 
par(mfrow=c(1,2),mai=c(1,0.5,1,0.5))
hist(ranef(models[["Shan"]])$individual[["(Intercept)"]],
     xlab=names(ranef(models[["Shan"]])$individual)[[1]],main="max size")     

qqnorm(ranef(models[["Shan"]])$individual[["(Intercept)"]],
       ylab=paste("Sample Quantiles",
                  names(ranef(models[["Shan"]])$individual)[[1]]))
qqline(ranef(models[["Shan"]])$individual[["(Intercept)"]])

#Random effects of intercept for linear mixed model of Interpolated/Extrapolated Shannon Diversity (using min reference size).
# Residuals for each individual
plot(models[["Shan"]], individual ~ resid(., scaled=TRUE), 
     main="Residuals of Individual (Averaged over Week)")

# Plot of intercept of random effect
dotplot(ranef(models[["Shan"]],condVar=TRUE), scales = list(x = list(relation = "free")))


tableCI_Shan_min_size<-xtable(confint_lmer[["Shan"]]$value)
# 95 Percent Bootstrapped Confidence Intervals forLMM of Interpolated/Extrapolated Shannon Diversity"
# The LMERConvenienceFunctions looks at the standard deviations above or below the mean. 
# In this case, I am using 3 standard deviations. Checking for outliers with 
# LMERConvenienceFunctions for Interpolated/Extrapolated Shannon Diversity
# (using min reference size) using 3 standard deviations above and below the mean

# checking how many outliers there are
mcp.fnc(models[["Shan"]], trim = 3)

diversity.trimmed.Shan = romr.fnc(models[["Shan"]], diversity_min_size, trim = 3)

tmp=diversity.trimmed.Shan$data
tmp$trimmed=T
tmp1=diversity.trimmed.Shan$data0
tmp1$orig=T
tmp2=merge(tmp,tmp1,all=TRUE,by=names(tmp)[-which(names(tmp)=="trimmed")])
tmp3=tmp2[which(is.na(tmp2$trimmed)),-c(which(names(tmp2)=="trimmed"),which(names(tmp2)=="wd"),which(names(tmp2)=="rstand"),which(names(tmp2)=="orig"))]
table_Shanoutlier<-xtable(tmp3)
label(table_Shanoutlier)<-"Table: OutlierShan"
rm(tmp,tmp1,tmp2,tmp3)

table_Shanoutlier

modelShan<-lmer(Shan ~ diet*week+(1|individual), data = diversity.trimmed.Shan$data)

mcp.fnc(modelShan, trim = 3)

diversity.trimmed2 = romr.fnc(modelShan, diversity.trimmed.Shan$data, trim = 3)

#Residuals vs fitted and QQPlot of LMM with random intercept for Shan after removing 2nd set of outliers
par(mfrow=c(1,2),mai=c(1,0.5,1,0.5))
plot.glmer(modelShan,title="H without outliers")

# Histogram and QQ plots of fitted random intercept for Shan after removing second set of outliers based on 3 s.d.
par(mfrow=c(1,2),mai=c(1,0.5,1,0.5))
hist(ranef(modelShan)$individual[["(Intercept)"]],xlab=names(ranef(modelShan)$individual)[[1]],main="")     

qqnorm(ranef(modelShan)$individual[["(Intercept)"]],ylab=paste("Sample Quantiles",names(ranef(modelShan)$individual)[[1]]))
qqline(ranef(modelShan)$individual[["(Intercept)"]])

# Random effects of intercept for linear mixed model of Shan after removing second set of outliers
# Residuals for each individual
plot(modelShan, individual ~ resid(., scaled=TRUE), main="Residuals of Individual 
     (Averaging across Weeks)")

# Plot of intercept of random effect
dotplot(ranef(modelShan,condVar=TRUE), scales = list(x = list(relation = "free")))

confint_lmer_outlier2_Shan <-tryCatch.W.E(confint(modelShan,method="boot",nsim=boot_sims, boot.type="perc"))

# 95% Bootstrapped Confidence Intervals for LMM of Shan after removing one outlier, DF_5_4.
tableCI2_outlier2_Shan<-xtable(confint_lmer_outlier2_Shan$value)
View(tableCI2_outlier2_Shan)

# In the paper, we used the supplemental info and figure that keeps the outlier 
# due to there not being a major change that would change the overall conclusion of the paper
# Plus, we did not remove this outlier in Species Richness
# Code adapted from http://glmm.wikidot.com/faq  
newdat_HN <- expand.grid(week0 = 1:8, diet=c("DF","HN"),`Shan`= 0)
newdat_LN <- expand.grid(week0 = 1:4, diet=c("LN"),`Shan`= 0)
newdat <- rbind(newdat_HN, newdat_LN)
mm <- model.matrix(terms(models[["Shan"]]),newdat)
newdat$`Shan`<-mm %*% fixef(models[["Shan"]])
# or predict(modelShan,newdat,re.form=NA)
pvar1 <- diag(mm %*% tcrossprod(vcov(models[["Shan"]]),mm))
tvar1 <- pvar1+VarCorr(models[["Shan"]])$individual[1]## must be adapted for more complex models
newdat <- data.frame(
  newdat
  , plo = newdat$`Shan`-2*sqrt(pvar1)
  , phi = newdat$`Shan`+2*sqrt(pvar1)
  , tlo = newdat$`Shan`-2*sqrt(tvar1)
  , thi = newdat$`Shan`+2*sqrt(tvar1)
)
names(newdat)[names(newdat)=="q...0"] ="Shan"
require(ggplot2)
newdat$colors[newdat$diet=="DF"]="black"
newdat$colors[newdat$diet=="HN"]="cyan4"
newdat$colors[newdat$diet=="LN"]="darkorange"

newdat$colorsfill[newdat$diet=="DF"]="black"
newdat$colorsfill[newdat$diet=="HN"]="cyan4"
newdat$colorsfill[newdat$diet=="LN"]="darkorange"

newdat$shape[newdat$diet=="DF"]=22
newdat$shape[newdat$diet=="HN"]=21
newdat$shape[newdat$diet=="LN"]=23

newdat$lt[newdat$diet=="DF"]="solid"
newdat$lt[newdat$diet=="HN"]="solid"
newdat$lt[newdat$diet=="LN"]="solid"

write.csv(newdat, "/Users/kaylacross/Library/CloudStorage/OneDrive-TheOhioStateUniversity/Frass_Paper/Sabree_L5/plots wo cellulose 5 8/L5 diversity/rerun_code/ShanRich_nocell58_newdat.csv")

#plot confidence
g0 <- ggplot(newdat, aes(x=week0, y=`Shan`))+
  geom_point(colour=newdat$colors,
             fill=newdat$colorsfill,shape=newdat$shape, cex=4)
g0 + geom_errorbar(aes(ymin = plo, ymax = phi),colour=newdat$colors,cex=1, linetype=newdat$lt) +
  labs (x ="Week", y = "Shannon") +
  theme(panel.background = element_blank(), axis.line = element_line(colour = "black",size=1),
        axis.title = element_text(size=20),
        axis.text = element_text(size=15))
# plot looks good and reruning code gave the same results as when I ran this code for the paper

